# Generated by Django 5.0.14 on 2025-08-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity_date', models.DateField(verbose_name='validity date')),
                ('created_date', models.DateField(verbose_name='created date')),
                ('c_eur', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='EUR')),
                ('c_czk', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='CZK')),
                ('c_pln', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='PLN')),
                ('c_huf', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='HUF')),
                ('c_huf_amount', models.PositiveIntegerField(default=1, verbose_name='HUF amount')),
                ('c_usd', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='USD')),
                ('c_jpy', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='JPY')),
                ('c_jpy_amount', models.PositiveIntegerField(default=1, verbose_name='JPY amount')),
                ('c_bgn', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='BGN')),
                ('c_dkk', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='DKK')),
                ('c_gbp', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='GBP')),
                ('c_ron', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='RON')),
                ('c_sek', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='SEK')),
                ('c_chf', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='CHF')),
                ('c_isk', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='ISK')),
                ('c_isk_amount', models.PositiveIntegerField(default=1, verbose_name='ISK amount')),
                ('c_nok', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='NOK')),
                ('c_hrk', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='HRK')),
                ('c_try', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='TRY')),
                ('c_aud', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='AUD')),
                ('c_brl', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='BRL')),
                ('c_cad', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='CAD')),
                ('c_cny', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='CNY')),
                ('c_hkd', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='HKD')),
                ('c_idr', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='IDR')),
                ('c_idr_amount', models.PositiveIntegerField(default=1, verbose_name='IDR amount')),
                ('c_ils', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='ILS')),
                ('c_inr', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='INR')),
                ('c_inr_amount', models.PositiveIntegerField(default=1, verbose_name='INR amount')),
                ('c_krw', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='KRW')),
                ('c_krw_amount', models.PositiveIntegerField(default=1, verbose_name='KRW amount')),
                ('c_mxn', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='MXN')),
                ('c_myr', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='MYR')),
                ('c_nzd', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='NZD')),
                ('c_php', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='PHP')),
                ('c_php_amount', models.PositiveIntegerField(default=1, verbose_name='PHP amount')),
                ('c_sgd', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='SGD')),
                ('c_thb', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='THB')),
                ('c_thb_amount', models.PositiveIntegerField(default=1, verbose_name='THB amount')),
                ('c_zar', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True, verbose_name='ZAR')),
                ('fixed_base_currency', models.BooleanField(default=True, verbose_name='customer')),
                ('source', models.CharField(choices=[('ECB', 'ECB'), ('CNB', 'CNB'), ('NBP', 'NBP'), ('MNB', 'MNB'), ('RNB', 'RNB'), ('BOE', 'BOE')], default='ECB', max_length=10, verbose_name='source')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'unique_together': {('validity_date', 'source')},
            },
        ),
    ]
